[
  ./lib/attrsets.nix
  ./lib/clean-source.nix
  ./lib/dhall.nix
  ./lib/directory.nix
  ./lib/dns.nix
  ./lib/emacs.nix
  ./lib/ipaddr.nix
  ./lib/maintainers.nix
  ./lib/dhess-lib-nix.nix
  ./lib/operators.nix
  ./lib/secrets.nix
  ./lib/security.nix
  ./lib/testing.nix
  ./lib/types.nix
  ./haskell/lib.nix
]
